# Generated by Django 3.1.3 on 2020-11-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('small_or_large', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('crust', models.CharField(choices=[('CB', 'cheese burst'), ('CHT', 'classic hand tossed'), ('WTC', 'wheat thin crust'), ('FPP', 'fresh pan pizza'), ('NHT', 'new hand tossed')], default='FPP', max_length=50)),
                ('veg_nonveg', models.BooleanField(default=False)),
            ],
        ),
    ]
